# James Olal Personal Website Configuration
# https://olalkeith.github.io/olal-james/

# Jekyll site settings

title: James Olal
tagline: Software Developer in Nairobi
email: jkeneth.jk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  James Olal is a Software Developer based in Nairobi, Kenya. Specializing in React, Flutter, and full-stack development.
baseurl: "/olal-james" # the subpath of your site, e.g. /blog
url: "https://olalkeith.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Africa/Nairobi

# Default permalink style
permalink: /:categories/:year/:month/:day/:slug

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Theme
plainwhite:
  name: James Olal
  tagline: Software Developer in Nairobi

  favicon:
    default_16x16: assets/images/profile.png
    default_32x32: assets/images/profile.png
    default_64x64: assets/images/profile.png
    default_96x96: assets/images/profile.png

  portfolio_image:
    default: assets/images/profile.png

  portfolio_image_dark:
    default: assets/images/profile.png

  sitemap: true
  search: false
  dark_mode: true
  html_lang: "en"
  condensed_mobile:
    - page
    - post
    - post_list
  social_links:
    bluesky: ""
    github: OlalKeith
    linkedin: james-olal
    email: jkeneth.jk@gmail.com

  navigation:
    - title: About Me
      url: /
    - title: Projects
      url: /projects
    - title: Today I Learned
      url: /til/

  analytics_id: "G-XMT4SC8QXQ"

# social config is used in jekyll-seo-tag JSON-LD output.
social:
  name: James Olal
  links:
    - https://github.com/OlalKeith
    - https://www.linkedin.com/in/james-olal/

# twitter is used by jekyll-seo-tag
twitter:
  # username is used for twitter:site
  username: ""

pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: date
  sort_reverse: true

include:
  - .well-known/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - aqua-checksums.json
  - aqua.yaml
  - gemfiles/
  - node_modules/
  - tools/
  - CODE_OF_CONDUCT.md
  - CODEOWNERS
  - CONTRIBUTING.md
  - SECURITY.md
  - README.md
  - Makefile
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - renovate.json5
  - requirements.txt
  - til.sh